### Get all categories
GET http://localhost:9000/api/categories
X-API-Key: SECRET
Accept: application/json

### Create new category
POST http://localhost:9000/api/categories
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Fresh"
}

### Get category by Id
GET http://localhost:9000/api/categories/5
X-API-Key: SECRET
Accept: application/json

### Update category by Id
PUT http://localhost:9000/api/categories/4
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Gaming Chair"
}

### Delete category by Id
DELETE http://localhost:9000/api/categories/4
X-API-Key: SECRET
Accept: application/json
